Select id, code, categoryid, name, price, stock, saleprice, tax, discount, brandname, catalog, remarks, updatedby, updatedone, discontinued, reasondiscont, image, companyname from usersdb.items
USE usersdb;

insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (2,'DDBB',null,'SWEET',222,3000,null,'10','20','BRAND N',null,null,null,null,'0',null,null,'Amma''s grocery');
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (3,'DDD111',15,'RAVA',0,0,null,'1','2',null,null,null,null,null,'n',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (5,'DD1D',16,'DAL',10,200,null,'1','1',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (6,'PODIJAM',16,'JAM',10,200,null,'1','1',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (7,'PODIRAC',16,'DLY PODI',10,200,null,'1','1',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (8,'SUNNY',17,'VEG',10,200,null,'1','1',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (15,'NEWS',18,null,0,0,null,'1','0',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (16,'NEWS',18,null,0,0,null,'1','0',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (17,'NEWS',19,null,0,0,null,'1','0',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (19,'ITEMNEW',25,null,0,0,null,'1','0',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (20,'ITEMNEW',26,null,0,0,null,'1','0',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (21,'ITEMNEW',28,null,0,0,null,'1','0',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (22,'ITEMN11',null,null,0,0,null,'1','0',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (23,'EEEEBB',15,'NEW1_6SWEET',12,10000,null,'10','20','BRAND N','12 nla','ddddd 12','MEME 121',' DONE 112','0','1211',null,'Amma''s grocery');
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (24,'JJEEBB',null,'NEW1_6SWEET',12,10000,null,'10','20','BRAND N','12 nla','ddddd 12','MEME 121',' DONE 112','0','1211',null,'Amma''s grocery');
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (25,'AADDBB',null,'NEW1_6SWEET',12,10000,null,'0','0',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (26,'NEWDBB',null,'NEW1_6SWEET',12,10000,null,'0','0',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (27,'UUBB',null,'SWEET',222,3000,null,'10','20','BRAND N',null,null,null,null,'0',null,null,'Amma''s grocery');
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (28,'SSSBB',null,'SWEET',222,3000,null,'10','20','BRAND N',null,null,null,null,'0',null,null,'Amma''s grocery');
