Select user_id, username, password, email, PHONE, FAX, ADD1, ADD2, ADD3, CARDNO, CARDEXPDT, AccountId, Age from usersdb.users
USE usersdb;

insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (25,'Usha_Chacko12','fgdfhdhNew','emailNew25','934 67 45455555','230 456 6788','add25122262','add2','add325','cardNOOOONEW11',null,'ACCT_26',67);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (26,'Adhi','fgdfhdhNew','emailNew','510 4545 4545','345 456677868','add1 26','add226','add3 26','NEWCARD123',null,'NEWCAR_26',0);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (27,'Amma','fgdfhdhNew','emailNew','415 456 5678',null,'',null,null,null,null,null,0);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (30,'Usha_Chacko','fgdfhdhNew','ushach@yahoo.com','934 67 4545','230 456 6788','Amdot lake1','ca','94568',null,null,null,0);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (31,'Shasha_Chacko','fgdfhdhNew','ushach@yahoo.com','934 67 4545','230 456 6788','Amdot lake1','ca','94568',null,null,null,0);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (32,'Usha_Chacko','fgdfhdhNew','emailNew','934 67 4545','230 456 6788','add1','add2','add325',null,null,null,0);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (33,'Usha_Chacko','fgdfhdhNew','emailNew','934 67 4545','230 456 6788','add1','add2','add325',null,null,null,0);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (34,'Usha_Chacko','fgdfhdhNew','emailNew','934 67 4545','230 456 6788','add1','add2','add325','carddfsd1234',null,null,0);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (35,'Usha_Chacko','fgdfhdhNew','emailNew','934 67 4545','230 456 6788','add1','add2','add325','cardNofsd1234',null,null,0);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (36,'dfgNewUsha_Chacko',null,'emailNew','912345667',null,'fgdfhdhNew',null,null,null,null,'ACCT_ID',35);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (37,'dfgNewUsha_Chacko',null,'emailNew','912345667',null,'fgdfhdhNew',null,null,null,null,'ACCT_ID',35);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (38,'dfgNewUsha_Chacko',null,'emailNew','912345667',null,'fgdfhdhNew',null,null,null,null,'ACCT_7775',35);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (40,'dfgNewUsha_Chacko',null,'emailNew','912345667',null,'fgdfhdhNew',null,null,null,null,'ACCT_7775',35);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (41,'dfgNewUsha_Chacko',null,'emailNew','912345667',null,'fgdfhdhNew',null,null,null,null,'ACCT_7775',35);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (42,'dfgNewUsha_Chacko',null,'emailNew','912345667',null,'fgdfhdhNew',null,null,null,null,'ACCT_7775',35);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (43,'dfgNewUsha_Chacko',null,'emailNew','912345667',null,'fgdfhdhNew',null,null,null,null,'ACCT_7775',35);
insert into `users`(`user_id`,`username`,`password`,`email`,`PHONE`,`FAX`,`ADD1`,`ADD2`,`ADD3`,`CARDNO`,`CARDEXPDT`,`AccountId`,`Age`) values (44,'Adhvaidh',null,null,null,null,null,null,null,null,null,null,0);
