Select id, code, categoryid, name, price, stock, saleprice, tax, discount, brandname, catalog, remarks, updatedby, updatedone, discontinued, reasondiscont, image, companyname from test.items
USE test;

insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (2,'DDBB',1,'SWEET',12,10000,null,'10','20','BRAND N','12 nla','ddddd 12','MEME 121',' DONE 112','0','1211',null,'Amma''s grocery');
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (3,'DDD111',1,'RAVA',0,0,null,'1','2',null,null,null,null,null,'n',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (5,'DD1D',2,'DAL',10,200,null,'1','1',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (6,'PODIJAM',2,'JAM',10,200,null,'1','1',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (7,'PODIRAC',2,'DLY PODI',10,200,null,'1','1',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (8,'PODI_RASAM',3,'VEG',10,200,null,'1','1',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (15,'NEWS',13,null,0,0,null,'1','0',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (16,'NEWS',14,null,0,0,null,'1','0',null,null,null,null,null,'0',null,null,null);
insert into `items`(`id`,`code`,`categoryid`,`name`,`price`,`stock`,`saleprice`,`tax`,`discount`,`brandname`,`catalog`,`remarks`,`updatedby`,`updatedone`,`discontinued`,`reasondiscont`,`image`,`companyname`) values (17,'NEWS',1,null,0,0,null,'1','0',null,null,null,null,null,'0',null,null,null);
